// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subscription.proto

package org.bitcoin.protocols.subscriptions;

public final class Protos {
  private Protos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SubscriptionPaymentOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bytes contract_id = 1;
    /**
     * <code>required bytes contract_id = 1;</code>
     */
    boolean hasContractId();
    /**
     * <code>required bytes contract_id = 1;</code>
     */
    com.google.protobuf.ByteString getContractId();

    // required .payments.PaymentDetails payment_for_contract = 2;
    /**
     * <code>required .payments.PaymentDetails payment_for_contract = 2;</code>
     */
    boolean hasPaymentForContract();
    /**
     * <code>required .payments.PaymentDetails payment_for_contract = 2;</code>
     */
    org.bitcoin.protocols.payments.Protos.PaymentDetails getPaymentForContract();
    /**
     * <code>required .payments.PaymentDetails payment_for_contract = 2;</code>
     */
    org.bitcoin.protocols.payments.Protos.PaymentDetailsOrBuilder getPaymentForContractOrBuilder();
  }
  /**
   * Protobuf type {@code payments.SubscriptionPayment}
   */
  public static final class SubscriptionPayment extends
      com.google.protobuf.GeneratedMessage
      implements SubscriptionPaymentOrBuilder {
    // Use SubscriptionPayment.newBuilder() to construct.
    private SubscriptionPayment(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SubscriptionPayment(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SubscriptionPayment defaultInstance;
    public static SubscriptionPayment getDefaultInstance() {
      return defaultInstance;
    }

    public SubscriptionPayment getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SubscriptionPayment(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              contractId_ = input.readBytes();
              break;
            }
            case 18: {
              org.bitcoin.protocols.payments.Protos.PaymentDetails.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = paymentForContract_.toBuilder();
              }
              paymentForContract_ = input.readMessage(org.bitcoin.protocols.payments.Protos.PaymentDetails.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(paymentForContract_);
                paymentForContract_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bitcoin.protocols.subscriptions.Protos.internal_static_payments_SubscriptionPayment_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bitcoin.protocols.subscriptions.Protos.internal_static_payments_SubscriptionPayment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment.class, org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment.Builder.class);
    }

    public static com.google.protobuf.Parser<SubscriptionPayment> PARSER =
        new com.google.protobuf.AbstractParser<SubscriptionPayment>() {
      public SubscriptionPayment parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SubscriptionPayment(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SubscriptionPayment> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bytes contract_id = 1;
    public static final int CONTRACT_ID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString contractId_;
    /**
     * <code>required bytes contract_id = 1;</code>
     */
    public boolean hasContractId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes contract_id = 1;</code>
     */
    public com.google.protobuf.ByteString getContractId() {
      return contractId_;
    }

    // required .payments.PaymentDetails payment_for_contract = 2;
    public static final int PAYMENT_FOR_CONTRACT_FIELD_NUMBER = 2;
    private org.bitcoin.protocols.payments.Protos.PaymentDetails paymentForContract_;
    /**
     * <code>required .payments.PaymentDetails payment_for_contract = 2;</code>
     */
    public boolean hasPaymentForContract() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .payments.PaymentDetails payment_for_contract = 2;</code>
     */
    public org.bitcoin.protocols.payments.Protos.PaymentDetails getPaymentForContract() {
      return paymentForContract_;
    }
    /**
     * <code>required .payments.PaymentDetails payment_for_contract = 2;</code>
     */
    public org.bitcoin.protocols.payments.Protos.PaymentDetailsOrBuilder getPaymentForContractOrBuilder() {
      return paymentForContract_;
    }

    private void initFields() {
      contractId_ = com.google.protobuf.ByteString.EMPTY;
      paymentForContract_ = org.bitcoin.protocols.payments.Protos.PaymentDetails.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasContractId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPaymentForContract()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getPaymentForContract().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, contractId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, paymentForContract_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, contractId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, paymentForContract_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code payments.SubscriptionPayment}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.bitcoin.protocols.subscriptions.Protos.SubscriptionPaymentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.bitcoin.protocols.subscriptions.Protos.internal_static_payments_SubscriptionPayment_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.bitcoin.protocols.subscriptions.Protos.internal_static_payments_SubscriptionPayment_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment.class, org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment.Builder.class);
      }

      // Construct using org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPaymentForContractFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        contractId_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (paymentForContractBuilder_ == null) {
          paymentForContract_ = org.bitcoin.protocols.payments.Protos.PaymentDetails.getDefaultInstance();
        } else {
          paymentForContractBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.bitcoin.protocols.subscriptions.Protos.internal_static_payments_SubscriptionPayment_descriptor;
      }

      public org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment getDefaultInstanceForType() {
        return org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment.getDefaultInstance();
      }

      public org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment build() {
        org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment buildPartial() {
        org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment result = new org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.contractId_ = contractId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (paymentForContractBuilder_ == null) {
          result.paymentForContract_ = paymentForContract_;
        } else {
          result.paymentForContract_ = paymentForContractBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment) {
          return mergeFrom((org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment other) {
        if (other == org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment.getDefaultInstance()) return this;
        if (other.hasContractId()) {
          setContractId(other.getContractId());
        }
        if (other.hasPaymentForContract()) {
          mergePaymentForContract(other.getPaymentForContract());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasContractId()) {
          
          return false;
        }
        if (!hasPaymentForContract()) {
          
          return false;
        }
        if (!getPaymentForContract().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bytes contract_id = 1;
      private com.google.protobuf.ByteString contractId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes contract_id = 1;</code>
       */
      public boolean hasContractId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes contract_id = 1;</code>
       */
      public com.google.protobuf.ByteString getContractId() {
        return contractId_;
      }
      /**
       * <code>required bytes contract_id = 1;</code>
       */
      public Builder setContractId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        contractId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes contract_id = 1;</code>
       */
      public Builder clearContractId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        contractId_ = getDefaultInstance().getContractId();
        onChanged();
        return this;
      }

      // required .payments.PaymentDetails payment_for_contract = 2;
      private org.bitcoin.protocols.payments.Protos.PaymentDetails paymentForContract_ = org.bitcoin.protocols.payments.Protos.PaymentDetails.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.bitcoin.protocols.payments.Protos.PaymentDetails, org.bitcoin.protocols.payments.Protos.PaymentDetails.Builder, org.bitcoin.protocols.payments.Protos.PaymentDetailsOrBuilder> paymentForContractBuilder_;
      /**
       * <code>required .payments.PaymentDetails payment_for_contract = 2;</code>
       */
      public boolean hasPaymentForContract() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .payments.PaymentDetails payment_for_contract = 2;</code>
       */
      public org.bitcoin.protocols.payments.Protos.PaymentDetails getPaymentForContract() {
        if (paymentForContractBuilder_ == null) {
          return paymentForContract_;
        } else {
          return paymentForContractBuilder_.getMessage();
        }
      }
      /**
       * <code>required .payments.PaymentDetails payment_for_contract = 2;</code>
       */
      public Builder setPaymentForContract(org.bitcoin.protocols.payments.Protos.PaymentDetails value) {
        if (paymentForContractBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          paymentForContract_ = value;
          onChanged();
        } else {
          paymentForContractBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .payments.PaymentDetails payment_for_contract = 2;</code>
       */
      public Builder setPaymentForContract(
          org.bitcoin.protocols.payments.Protos.PaymentDetails.Builder builderForValue) {
        if (paymentForContractBuilder_ == null) {
          paymentForContract_ = builderForValue.build();
          onChanged();
        } else {
          paymentForContractBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .payments.PaymentDetails payment_for_contract = 2;</code>
       */
      public Builder mergePaymentForContract(org.bitcoin.protocols.payments.Protos.PaymentDetails value) {
        if (paymentForContractBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              paymentForContract_ != org.bitcoin.protocols.payments.Protos.PaymentDetails.getDefaultInstance()) {
            paymentForContract_ =
              org.bitcoin.protocols.payments.Protos.PaymentDetails.newBuilder(paymentForContract_).mergeFrom(value).buildPartial();
          } else {
            paymentForContract_ = value;
          }
          onChanged();
        } else {
          paymentForContractBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .payments.PaymentDetails payment_for_contract = 2;</code>
       */
      public Builder clearPaymentForContract() {
        if (paymentForContractBuilder_ == null) {
          paymentForContract_ = org.bitcoin.protocols.payments.Protos.PaymentDetails.getDefaultInstance();
          onChanged();
        } else {
          paymentForContractBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .payments.PaymentDetails payment_for_contract = 2;</code>
       */
      public org.bitcoin.protocols.payments.Protos.PaymentDetails.Builder getPaymentForContractBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getPaymentForContractFieldBuilder().getBuilder();
      }
      /**
       * <code>required .payments.PaymentDetails payment_for_contract = 2;</code>
       */
      public org.bitcoin.protocols.payments.Protos.PaymentDetailsOrBuilder getPaymentForContractOrBuilder() {
        if (paymentForContractBuilder_ != null) {
          return paymentForContractBuilder_.getMessageOrBuilder();
        } else {
          return paymentForContract_;
        }
      }
      /**
       * <code>required .payments.PaymentDetails payment_for_contract = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.bitcoin.protocols.payments.Protos.PaymentDetails, org.bitcoin.protocols.payments.Protos.PaymentDetails.Builder, org.bitcoin.protocols.payments.Protos.PaymentDetailsOrBuilder> 
          getPaymentForContractFieldBuilder() {
        if (paymentForContractBuilder_ == null) {
          paymentForContractBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.bitcoin.protocols.payments.Protos.PaymentDetails, org.bitcoin.protocols.payments.Protos.PaymentDetails.Builder, org.bitcoin.protocols.payments.Protos.PaymentDetailsOrBuilder>(
                  paymentForContract_,
                  getParentForChildren(),
                  isClean());
          paymentForContract_ = null;
        }
        return paymentForContractBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:payments.SubscriptionPayment)
    }

    static {
      defaultInstance = new SubscriptionPayment(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:payments.SubscriptionPayment)
  }

  public interface SubscriptionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional uint32 subscription_version = 1 [default = 1];
    /**
     * <code>optional uint32 subscription_version = 1 [default = 1];</code>
     */
    boolean hasSubscriptionVersion();
    /**
     * <code>optional uint32 subscription_version = 1 [default = 1];</code>
     */
    int getSubscriptionVersion();

    // required string merchant_id = 2;
    /**
     * <code>required string merchant_id = 2;</code>
     */
    boolean hasMerchantId();
    /**
     * <code>required string merchant_id = 2;</code>
     */
    java.lang.String getMerchantId();
    /**
     * <code>required string merchant_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getMerchantIdBytes();

    // required bytes subscription_id = 3;
    /**
     * <code>required bytes subscription_id = 3;</code>
     */
    boolean hasSubscriptionId();
    /**
     * <code>required bytes subscription_id = 3;</code>
     */
    com.google.protobuf.ByteString getSubscriptionId();

    // required .payments.PaymentDetails subscription_contracts = 4;
    /**
     * <code>required .payments.PaymentDetails subscription_contracts = 4;</code>
     */
    boolean hasSubscriptionContracts();
    /**
     * <code>required .payments.PaymentDetails subscription_contracts = 4;</code>
     */
    org.bitcoin.protocols.payments.Protos.PaymentDetails getSubscriptionContracts();
    /**
     * <code>required .payments.PaymentDetails subscription_contracts = 4;</code>
     */
    org.bitcoin.protocols.payments.Protos.PaymentDetailsOrBuilder getSubscriptionContractsOrBuilder();

    // repeated .payments.SubscriptionPayment payments_for_period = 5;
    /**
     * <code>repeated .payments.SubscriptionPayment payments_for_period = 5;</code>
     */
    java.util.List<org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment> 
        getPaymentsForPeriodList();
    /**
     * <code>repeated .payments.SubscriptionPayment payments_for_period = 5;</code>
     */
    org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment getPaymentsForPeriod(int index);
    /**
     * <code>repeated .payments.SubscriptionPayment payments_for_period = 5;</code>
     */
    int getPaymentsForPeriodCount();
    /**
     * <code>repeated .payments.SubscriptionPayment payments_for_period = 5;</code>
     */
    java.util.List<? extends org.bitcoin.protocols.subscriptions.Protos.SubscriptionPaymentOrBuilder> 
        getPaymentsForPeriodOrBuilderList();
    /**
     * <code>repeated .payments.SubscriptionPayment payments_for_period = 5;</code>
     */
    org.bitcoin.protocols.subscriptions.Protos.SubscriptionPaymentOrBuilder getPaymentsForPeriodOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code payments.Subscription}
   */
  public static final class Subscription extends
      com.google.protobuf.GeneratedMessage
      implements SubscriptionOrBuilder {
    // Use Subscription.newBuilder() to construct.
    private Subscription(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Subscription(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Subscription defaultInstance;
    public static Subscription getDefaultInstance() {
      return defaultInstance;
    }

    public Subscription getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Subscription(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              subscriptionVersion_ = input.readUInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              merchantId_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              subscriptionId_ = input.readBytes();
              break;
            }
            case 34: {
              org.bitcoin.protocols.payments.Protos.PaymentDetails.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = subscriptionContracts_.toBuilder();
              }
              subscriptionContracts_ = input.readMessage(org.bitcoin.protocols.payments.Protos.PaymentDetails.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(subscriptionContracts_);
                subscriptionContracts_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                paymentsForPeriod_ = new java.util.ArrayList<org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment>();
                mutable_bitField0_ |= 0x00000010;
              }
              paymentsForPeriod_.add(input.readMessage(org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          paymentsForPeriod_ = java.util.Collections.unmodifiableList(paymentsForPeriod_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bitcoin.protocols.subscriptions.Protos.internal_static_payments_Subscription_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bitcoin.protocols.subscriptions.Protos.internal_static_payments_Subscription_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.bitcoin.protocols.subscriptions.Protos.Subscription.class, org.bitcoin.protocols.subscriptions.Protos.Subscription.Builder.class);
    }

    public static com.google.protobuf.Parser<Subscription> PARSER =
        new com.google.protobuf.AbstractParser<Subscription>() {
      public Subscription parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Subscription(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Subscription> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional uint32 subscription_version = 1 [default = 1];
    public static final int SUBSCRIPTION_VERSION_FIELD_NUMBER = 1;
    private int subscriptionVersion_;
    /**
     * <code>optional uint32 subscription_version = 1 [default = 1];</code>
     */
    public boolean hasSubscriptionVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 subscription_version = 1 [default = 1];</code>
     */
    public int getSubscriptionVersion() {
      return subscriptionVersion_;
    }

    // required string merchant_id = 2;
    public static final int MERCHANT_ID_FIELD_NUMBER = 2;
    private java.lang.Object merchantId_;
    /**
     * <code>required string merchant_id = 2;</code>
     */
    public boolean hasMerchantId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string merchant_id = 2;</code>
     */
    public java.lang.String getMerchantId() {
      java.lang.Object ref = merchantId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          merchantId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string merchant_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMerchantIdBytes() {
      java.lang.Object ref = merchantId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        merchantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required bytes subscription_id = 3;
    public static final int SUBSCRIPTION_ID_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString subscriptionId_;
    /**
     * <code>required bytes subscription_id = 3;</code>
     */
    public boolean hasSubscriptionId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes subscription_id = 3;</code>
     */
    public com.google.protobuf.ByteString getSubscriptionId() {
      return subscriptionId_;
    }

    // required .payments.PaymentDetails subscription_contracts = 4;
    public static final int SUBSCRIPTION_CONTRACTS_FIELD_NUMBER = 4;
    private org.bitcoin.protocols.payments.Protos.PaymentDetails subscriptionContracts_;
    /**
     * <code>required .payments.PaymentDetails subscription_contracts = 4;</code>
     */
    public boolean hasSubscriptionContracts() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required .payments.PaymentDetails subscription_contracts = 4;</code>
     */
    public org.bitcoin.protocols.payments.Protos.PaymentDetails getSubscriptionContracts() {
      return subscriptionContracts_;
    }
    /**
     * <code>required .payments.PaymentDetails subscription_contracts = 4;</code>
     */
    public org.bitcoin.protocols.payments.Protos.PaymentDetailsOrBuilder getSubscriptionContractsOrBuilder() {
      return subscriptionContracts_;
    }

    // repeated .payments.SubscriptionPayment payments_for_period = 5;
    public static final int PAYMENTS_FOR_PERIOD_FIELD_NUMBER = 5;
    private java.util.List<org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment> paymentsForPeriod_;
    /**
     * <code>repeated .payments.SubscriptionPayment payments_for_period = 5;</code>
     */
    public java.util.List<org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment> getPaymentsForPeriodList() {
      return paymentsForPeriod_;
    }
    /**
     * <code>repeated .payments.SubscriptionPayment payments_for_period = 5;</code>
     */
    public java.util.List<? extends org.bitcoin.protocols.subscriptions.Protos.SubscriptionPaymentOrBuilder> 
        getPaymentsForPeriodOrBuilderList() {
      return paymentsForPeriod_;
    }
    /**
     * <code>repeated .payments.SubscriptionPayment payments_for_period = 5;</code>
     */
    public int getPaymentsForPeriodCount() {
      return paymentsForPeriod_.size();
    }
    /**
     * <code>repeated .payments.SubscriptionPayment payments_for_period = 5;</code>
     */
    public org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment getPaymentsForPeriod(int index) {
      return paymentsForPeriod_.get(index);
    }
    /**
     * <code>repeated .payments.SubscriptionPayment payments_for_period = 5;</code>
     */
    public org.bitcoin.protocols.subscriptions.Protos.SubscriptionPaymentOrBuilder getPaymentsForPeriodOrBuilder(
        int index) {
      return paymentsForPeriod_.get(index);
    }

    private void initFields() {
      subscriptionVersion_ = 1;
      merchantId_ = "";
      subscriptionId_ = com.google.protobuf.ByteString.EMPTY;
      subscriptionContracts_ = org.bitcoin.protocols.payments.Protos.PaymentDetails.getDefaultInstance();
      paymentsForPeriod_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMerchantId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSubscriptionId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSubscriptionContracts()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getSubscriptionContracts().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPaymentsForPeriodCount(); i++) {
        if (!getPaymentsForPeriod(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, subscriptionVersion_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMerchantIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, subscriptionId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, subscriptionContracts_);
      }
      for (int i = 0; i < paymentsForPeriod_.size(); i++) {
        output.writeMessage(5, paymentsForPeriod_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, subscriptionVersion_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMerchantIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, subscriptionId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, subscriptionContracts_);
      }
      for (int i = 0; i < paymentsForPeriod_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, paymentsForPeriod_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.bitcoin.protocols.subscriptions.Protos.Subscription parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bitcoin.protocols.subscriptions.Protos.Subscription parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bitcoin.protocols.subscriptions.Protos.Subscription parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bitcoin.protocols.subscriptions.Protos.Subscription parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bitcoin.protocols.subscriptions.Protos.Subscription parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.bitcoin.protocols.subscriptions.Protos.Subscription parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.bitcoin.protocols.subscriptions.Protos.Subscription parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.bitcoin.protocols.subscriptions.Protos.Subscription parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.bitcoin.protocols.subscriptions.Protos.Subscription parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.bitcoin.protocols.subscriptions.Protos.Subscription parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.bitcoin.protocols.subscriptions.Protos.Subscription prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code payments.Subscription}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.bitcoin.protocols.subscriptions.Protos.SubscriptionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.bitcoin.protocols.subscriptions.Protos.internal_static_payments_Subscription_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.bitcoin.protocols.subscriptions.Protos.internal_static_payments_Subscription_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.bitcoin.protocols.subscriptions.Protos.Subscription.class, org.bitcoin.protocols.subscriptions.Protos.Subscription.Builder.class);
      }

      // Construct using org.bitcoin.protocols.subscriptions.Protos.Subscription.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSubscriptionContractsFieldBuilder();
          getPaymentsForPeriodFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        subscriptionVersion_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        merchantId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        subscriptionId_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (subscriptionContractsBuilder_ == null) {
          subscriptionContracts_ = org.bitcoin.protocols.payments.Protos.PaymentDetails.getDefaultInstance();
        } else {
          subscriptionContractsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        if (paymentsForPeriodBuilder_ == null) {
          paymentsForPeriod_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          paymentsForPeriodBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.bitcoin.protocols.subscriptions.Protos.internal_static_payments_Subscription_descriptor;
      }

      public org.bitcoin.protocols.subscriptions.Protos.Subscription getDefaultInstanceForType() {
        return org.bitcoin.protocols.subscriptions.Protos.Subscription.getDefaultInstance();
      }

      public org.bitcoin.protocols.subscriptions.Protos.Subscription build() {
        org.bitcoin.protocols.subscriptions.Protos.Subscription result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.bitcoin.protocols.subscriptions.Protos.Subscription buildPartial() {
        org.bitcoin.protocols.subscriptions.Protos.Subscription result = new org.bitcoin.protocols.subscriptions.Protos.Subscription(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.subscriptionVersion_ = subscriptionVersion_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.merchantId_ = merchantId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.subscriptionId_ = subscriptionId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (subscriptionContractsBuilder_ == null) {
          result.subscriptionContracts_ = subscriptionContracts_;
        } else {
          result.subscriptionContracts_ = subscriptionContractsBuilder_.build();
        }
        if (paymentsForPeriodBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            paymentsForPeriod_ = java.util.Collections.unmodifiableList(paymentsForPeriod_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.paymentsForPeriod_ = paymentsForPeriod_;
        } else {
          result.paymentsForPeriod_ = paymentsForPeriodBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.bitcoin.protocols.subscriptions.Protos.Subscription) {
          return mergeFrom((org.bitcoin.protocols.subscriptions.Protos.Subscription)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.bitcoin.protocols.subscriptions.Protos.Subscription other) {
        if (other == org.bitcoin.protocols.subscriptions.Protos.Subscription.getDefaultInstance()) return this;
        if (other.hasSubscriptionVersion()) {
          setSubscriptionVersion(other.getSubscriptionVersion());
        }
        if (other.hasMerchantId()) {
          bitField0_ |= 0x00000002;
          merchantId_ = other.merchantId_;
          onChanged();
        }
        if (other.hasSubscriptionId()) {
          setSubscriptionId(other.getSubscriptionId());
        }
        if (other.hasSubscriptionContracts()) {
          mergeSubscriptionContracts(other.getSubscriptionContracts());
        }
        if (paymentsForPeriodBuilder_ == null) {
          if (!other.paymentsForPeriod_.isEmpty()) {
            if (paymentsForPeriod_.isEmpty()) {
              paymentsForPeriod_ = other.paymentsForPeriod_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensurePaymentsForPeriodIsMutable();
              paymentsForPeriod_.addAll(other.paymentsForPeriod_);
            }
            onChanged();
          }
        } else {
          if (!other.paymentsForPeriod_.isEmpty()) {
            if (paymentsForPeriodBuilder_.isEmpty()) {
              paymentsForPeriodBuilder_.dispose();
              paymentsForPeriodBuilder_ = null;
              paymentsForPeriod_ = other.paymentsForPeriod_;
              bitField0_ = (bitField0_ & ~0x00000010);
              paymentsForPeriodBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPaymentsForPeriodFieldBuilder() : null;
            } else {
              paymentsForPeriodBuilder_.addAllMessages(other.paymentsForPeriod_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMerchantId()) {
          
          return false;
        }
        if (!hasSubscriptionId()) {
          
          return false;
        }
        if (!hasSubscriptionContracts()) {
          
          return false;
        }
        if (!getSubscriptionContracts().isInitialized()) {
          
          return false;
        }
        for (int i = 0; i < getPaymentsForPeriodCount(); i++) {
          if (!getPaymentsForPeriod(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.bitcoin.protocols.subscriptions.Protos.Subscription parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.bitcoin.protocols.subscriptions.Protos.Subscription) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional uint32 subscription_version = 1 [default = 1];
      private int subscriptionVersion_ = 1;
      /**
       * <code>optional uint32 subscription_version = 1 [default = 1];</code>
       */
      public boolean hasSubscriptionVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 subscription_version = 1 [default = 1];</code>
       */
      public int getSubscriptionVersion() {
        return subscriptionVersion_;
      }
      /**
       * <code>optional uint32 subscription_version = 1 [default = 1];</code>
       */
      public Builder setSubscriptionVersion(int value) {
        bitField0_ |= 0x00000001;
        subscriptionVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 subscription_version = 1 [default = 1];</code>
       */
      public Builder clearSubscriptionVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        subscriptionVersion_ = 1;
        onChanged();
        return this;
      }

      // required string merchant_id = 2;
      private java.lang.Object merchantId_ = "";
      /**
       * <code>required string merchant_id = 2;</code>
       */
      public boolean hasMerchantId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string merchant_id = 2;</code>
       */
      public java.lang.String getMerchantId() {
        java.lang.Object ref = merchantId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          merchantId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string merchant_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMerchantIdBytes() {
        java.lang.Object ref = merchantId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          merchantId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string merchant_id = 2;</code>
       */
      public Builder setMerchantId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        merchantId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string merchant_id = 2;</code>
       */
      public Builder clearMerchantId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        merchantId_ = getDefaultInstance().getMerchantId();
        onChanged();
        return this;
      }
      /**
       * <code>required string merchant_id = 2;</code>
       */
      public Builder setMerchantIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        merchantId_ = value;
        onChanged();
        return this;
      }

      // required bytes subscription_id = 3;
      private com.google.protobuf.ByteString subscriptionId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes subscription_id = 3;</code>
       */
      public boolean hasSubscriptionId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes subscription_id = 3;</code>
       */
      public com.google.protobuf.ByteString getSubscriptionId() {
        return subscriptionId_;
      }
      /**
       * <code>required bytes subscription_id = 3;</code>
       */
      public Builder setSubscriptionId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        subscriptionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes subscription_id = 3;</code>
       */
      public Builder clearSubscriptionId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        subscriptionId_ = getDefaultInstance().getSubscriptionId();
        onChanged();
        return this;
      }

      // required .payments.PaymentDetails subscription_contracts = 4;
      private org.bitcoin.protocols.payments.Protos.PaymentDetails subscriptionContracts_ = org.bitcoin.protocols.payments.Protos.PaymentDetails.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.bitcoin.protocols.payments.Protos.PaymentDetails, org.bitcoin.protocols.payments.Protos.PaymentDetails.Builder, org.bitcoin.protocols.payments.Protos.PaymentDetailsOrBuilder> subscriptionContractsBuilder_;
      /**
       * <code>required .payments.PaymentDetails subscription_contracts = 4;</code>
       */
      public boolean hasSubscriptionContracts() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required .payments.PaymentDetails subscription_contracts = 4;</code>
       */
      public org.bitcoin.protocols.payments.Protos.PaymentDetails getSubscriptionContracts() {
        if (subscriptionContractsBuilder_ == null) {
          return subscriptionContracts_;
        } else {
          return subscriptionContractsBuilder_.getMessage();
        }
      }
      /**
       * <code>required .payments.PaymentDetails subscription_contracts = 4;</code>
       */
      public Builder setSubscriptionContracts(org.bitcoin.protocols.payments.Protos.PaymentDetails value) {
        if (subscriptionContractsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          subscriptionContracts_ = value;
          onChanged();
        } else {
          subscriptionContractsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .payments.PaymentDetails subscription_contracts = 4;</code>
       */
      public Builder setSubscriptionContracts(
          org.bitcoin.protocols.payments.Protos.PaymentDetails.Builder builderForValue) {
        if (subscriptionContractsBuilder_ == null) {
          subscriptionContracts_ = builderForValue.build();
          onChanged();
        } else {
          subscriptionContractsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .payments.PaymentDetails subscription_contracts = 4;</code>
       */
      public Builder mergeSubscriptionContracts(org.bitcoin.protocols.payments.Protos.PaymentDetails value) {
        if (subscriptionContractsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              subscriptionContracts_ != org.bitcoin.protocols.payments.Protos.PaymentDetails.getDefaultInstance()) {
            subscriptionContracts_ =
              org.bitcoin.protocols.payments.Protos.PaymentDetails.newBuilder(subscriptionContracts_).mergeFrom(value).buildPartial();
          } else {
            subscriptionContracts_ = value;
          }
          onChanged();
        } else {
          subscriptionContractsBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .payments.PaymentDetails subscription_contracts = 4;</code>
       */
      public Builder clearSubscriptionContracts() {
        if (subscriptionContractsBuilder_ == null) {
          subscriptionContracts_ = org.bitcoin.protocols.payments.Protos.PaymentDetails.getDefaultInstance();
          onChanged();
        } else {
          subscriptionContractsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>required .payments.PaymentDetails subscription_contracts = 4;</code>
       */
      public org.bitcoin.protocols.payments.Protos.PaymentDetails.Builder getSubscriptionContractsBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getSubscriptionContractsFieldBuilder().getBuilder();
      }
      /**
       * <code>required .payments.PaymentDetails subscription_contracts = 4;</code>
       */
      public org.bitcoin.protocols.payments.Protos.PaymentDetailsOrBuilder getSubscriptionContractsOrBuilder() {
        if (subscriptionContractsBuilder_ != null) {
          return subscriptionContractsBuilder_.getMessageOrBuilder();
        } else {
          return subscriptionContracts_;
        }
      }
      /**
       * <code>required .payments.PaymentDetails subscription_contracts = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.bitcoin.protocols.payments.Protos.PaymentDetails, org.bitcoin.protocols.payments.Protos.PaymentDetails.Builder, org.bitcoin.protocols.payments.Protos.PaymentDetailsOrBuilder> 
          getSubscriptionContractsFieldBuilder() {
        if (subscriptionContractsBuilder_ == null) {
          subscriptionContractsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.bitcoin.protocols.payments.Protos.PaymentDetails, org.bitcoin.protocols.payments.Protos.PaymentDetails.Builder, org.bitcoin.protocols.payments.Protos.PaymentDetailsOrBuilder>(
                  subscriptionContracts_,
                  getParentForChildren(),
                  isClean());
          subscriptionContracts_ = null;
        }
        return subscriptionContractsBuilder_;
      }

      // repeated .payments.SubscriptionPayment payments_for_period = 5;
      private java.util.List<org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment> paymentsForPeriod_ =
        java.util.Collections.emptyList();
      private void ensurePaymentsForPeriodIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          paymentsForPeriod_ = new java.util.ArrayList<org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment>(paymentsForPeriod_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment, org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment.Builder, org.bitcoin.protocols.subscriptions.Protos.SubscriptionPaymentOrBuilder> paymentsForPeriodBuilder_;

      /**
       * <code>repeated .payments.SubscriptionPayment payments_for_period = 5;</code>
       */
      public java.util.List<org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment> getPaymentsForPeriodList() {
        if (paymentsForPeriodBuilder_ == null) {
          return java.util.Collections.unmodifiableList(paymentsForPeriod_);
        } else {
          return paymentsForPeriodBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .payments.SubscriptionPayment payments_for_period = 5;</code>
       */
      public int getPaymentsForPeriodCount() {
        if (paymentsForPeriodBuilder_ == null) {
          return paymentsForPeriod_.size();
        } else {
          return paymentsForPeriodBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .payments.SubscriptionPayment payments_for_period = 5;</code>
       */
      public org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment getPaymentsForPeriod(int index) {
        if (paymentsForPeriodBuilder_ == null) {
          return paymentsForPeriod_.get(index);
        } else {
          return paymentsForPeriodBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .payments.SubscriptionPayment payments_for_period = 5;</code>
       */
      public Builder setPaymentsForPeriod(
          int index, org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment value) {
        if (paymentsForPeriodBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePaymentsForPeriodIsMutable();
          paymentsForPeriod_.set(index, value);
          onChanged();
        } else {
          paymentsForPeriodBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .payments.SubscriptionPayment payments_for_period = 5;</code>
       */
      public Builder setPaymentsForPeriod(
          int index, org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment.Builder builderForValue) {
        if (paymentsForPeriodBuilder_ == null) {
          ensurePaymentsForPeriodIsMutable();
          paymentsForPeriod_.set(index, builderForValue.build());
          onChanged();
        } else {
          paymentsForPeriodBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .payments.SubscriptionPayment payments_for_period = 5;</code>
       */
      public Builder addPaymentsForPeriod(org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment value) {
        if (paymentsForPeriodBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePaymentsForPeriodIsMutable();
          paymentsForPeriod_.add(value);
          onChanged();
        } else {
          paymentsForPeriodBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .payments.SubscriptionPayment payments_for_period = 5;</code>
       */
      public Builder addPaymentsForPeriod(
          int index, org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment value) {
        if (paymentsForPeriodBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePaymentsForPeriodIsMutable();
          paymentsForPeriod_.add(index, value);
          onChanged();
        } else {
          paymentsForPeriodBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .payments.SubscriptionPayment payments_for_period = 5;</code>
       */
      public Builder addPaymentsForPeriod(
          org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment.Builder builderForValue) {
        if (paymentsForPeriodBuilder_ == null) {
          ensurePaymentsForPeriodIsMutable();
          paymentsForPeriod_.add(builderForValue.build());
          onChanged();
        } else {
          paymentsForPeriodBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .payments.SubscriptionPayment payments_for_period = 5;</code>
       */
      public Builder addPaymentsForPeriod(
          int index, org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment.Builder builderForValue) {
        if (paymentsForPeriodBuilder_ == null) {
          ensurePaymentsForPeriodIsMutable();
          paymentsForPeriod_.add(index, builderForValue.build());
          onChanged();
        } else {
          paymentsForPeriodBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .payments.SubscriptionPayment payments_for_period = 5;</code>
       */
      public Builder addAllPaymentsForPeriod(
          java.lang.Iterable<? extends org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment> values) {
        if (paymentsForPeriodBuilder_ == null) {
          ensurePaymentsForPeriodIsMutable();
          super.addAll(values, paymentsForPeriod_);
          onChanged();
        } else {
          paymentsForPeriodBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .payments.SubscriptionPayment payments_for_period = 5;</code>
       */
      public Builder clearPaymentsForPeriod() {
        if (paymentsForPeriodBuilder_ == null) {
          paymentsForPeriod_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          paymentsForPeriodBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .payments.SubscriptionPayment payments_for_period = 5;</code>
       */
      public Builder removePaymentsForPeriod(int index) {
        if (paymentsForPeriodBuilder_ == null) {
          ensurePaymentsForPeriodIsMutable();
          paymentsForPeriod_.remove(index);
          onChanged();
        } else {
          paymentsForPeriodBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .payments.SubscriptionPayment payments_for_period = 5;</code>
       */
      public org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment.Builder getPaymentsForPeriodBuilder(
          int index) {
        return getPaymentsForPeriodFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .payments.SubscriptionPayment payments_for_period = 5;</code>
       */
      public org.bitcoin.protocols.subscriptions.Protos.SubscriptionPaymentOrBuilder getPaymentsForPeriodOrBuilder(
          int index) {
        if (paymentsForPeriodBuilder_ == null) {
          return paymentsForPeriod_.get(index);  } else {
          return paymentsForPeriodBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .payments.SubscriptionPayment payments_for_period = 5;</code>
       */
      public java.util.List<? extends org.bitcoin.protocols.subscriptions.Protos.SubscriptionPaymentOrBuilder> 
           getPaymentsForPeriodOrBuilderList() {
        if (paymentsForPeriodBuilder_ != null) {
          return paymentsForPeriodBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(paymentsForPeriod_);
        }
      }
      /**
       * <code>repeated .payments.SubscriptionPayment payments_for_period = 5;</code>
       */
      public org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment.Builder addPaymentsForPeriodBuilder() {
        return getPaymentsForPeriodFieldBuilder().addBuilder(
            org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment.getDefaultInstance());
      }
      /**
       * <code>repeated .payments.SubscriptionPayment payments_for_period = 5;</code>
       */
      public org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment.Builder addPaymentsForPeriodBuilder(
          int index) {
        return getPaymentsForPeriodFieldBuilder().addBuilder(
            index, org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment.getDefaultInstance());
      }
      /**
       * <code>repeated .payments.SubscriptionPayment payments_for_period = 5;</code>
       */
      public java.util.List<org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment.Builder> 
           getPaymentsForPeriodBuilderList() {
        return getPaymentsForPeriodFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment, org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment.Builder, org.bitcoin.protocols.subscriptions.Protos.SubscriptionPaymentOrBuilder> 
          getPaymentsForPeriodFieldBuilder() {
        if (paymentsForPeriodBuilder_ == null) {
          paymentsForPeriodBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment, org.bitcoin.protocols.subscriptions.Protos.SubscriptionPayment.Builder, org.bitcoin.protocols.subscriptions.Protos.SubscriptionPaymentOrBuilder>(
                  paymentsForPeriod_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          paymentsForPeriod_ = null;
        }
        return paymentsForPeriodBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:payments.Subscription)
    }

    static {
      defaultInstance = new Subscription(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:payments.Subscription)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_payments_SubscriptionPayment_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_payments_SubscriptionPayment_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_payments_Subscription_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_payments_Subscription_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022subscription.proto\022\010payments\032\024paymentr" +
      "equest.proto\"b\n\023SubscriptionPayment\022\023\n\013c" +
      "ontract_id\030\001 \002(\014\0226\n\024payment_for_contract" +
      "\030\002 \002(\0132\030.payments.PaymentDetails\"\323\001\n\014Sub" +
      "scription\022\037\n\024subscription_version\030\001 \001(\r:" +
      "\0011\022\023\n\013merchant_id\030\002 \002(\t\022\027\n\017subscription_" +
      "id\030\003 \002(\014\0228\n\026subscription_contracts\030\004 \002(\013" +
      "2\030.payments.PaymentDetails\022:\n\023payments_f" +
      "or_period\030\005 \003(\0132\035.payments.SubscriptionP" +
      "aymentB-\n#org.bitcoin.protocols.subscrip",
      "tionsB\006Protos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_payments_SubscriptionPayment_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_payments_SubscriptionPayment_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_payments_SubscriptionPayment_descriptor,
              new java.lang.String[] { "ContractId", "PaymentForContract", });
          internal_static_payments_Subscription_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_payments_Subscription_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_payments_Subscription_descriptor,
              new java.lang.String[] { "SubscriptionVersion", "MerchantId", "SubscriptionId", "SubscriptionContracts", "PaymentsForPeriod", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.bitcoin.protocols.payments.Protos.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
