// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subscription.proto

package org.bitcoin.protocols.subscriptions;

public final class Protos {
  private Protos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SubscriptionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .payments.PaymentDetails contract = 1;
    /**
     * <code>required .payments.PaymentDetails contract = 1;</code>
     */
    boolean hasContract();
    /**
     * <code>required .payments.PaymentDetails contract = 1;</code>
     */
    org.bitcoin.protocols.payments.Protos.PaymentDetails getContract();
    /**
     * <code>required .payments.PaymentDetails contract = 1;</code>
     */
    org.bitcoin.protocols.payments.Protos.PaymentDetailsOrBuilder getContractOrBuilder();

    // repeated .payments.PaymentDetails payments_for_period = 2;
    /**
     * <code>repeated .payments.PaymentDetails payments_for_period = 2;</code>
     */
    java.util.List<org.bitcoin.protocols.payments.Protos.PaymentDetails> 
        getPaymentsForPeriodList();
    /**
     * <code>repeated .payments.PaymentDetails payments_for_period = 2;</code>
     */
    org.bitcoin.protocols.payments.Protos.PaymentDetails getPaymentsForPeriod(int index);
    /**
     * <code>repeated .payments.PaymentDetails payments_for_period = 2;</code>
     */
    int getPaymentsForPeriodCount();
    /**
     * <code>repeated .payments.PaymentDetails payments_for_period = 2;</code>
     */
    java.util.List<? extends org.bitcoin.protocols.payments.Protos.PaymentDetailsOrBuilder> 
        getPaymentsForPeriodOrBuilderList();
    /**
     * <code>repeated .payments.PaymentDetails payments_for_period = 2;</code>
     */
    org.bitcoin.protocols.payments.Protos.PaymentDetailsOrBuilder getPaymentsForPeriodOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code payments.Subscription}
   */
  public static final class Subscription extends
      com.google.protobuf.GeneratedMessage
      implements SubscriptionOrBuilder {
    // Use Subscription.newBuilder() to construct.
    private Subscription(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Subscription(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Subscription defaultInstance;
    public static Subscription getDefaultInstance() {
      return defaultInstance;
    }

    public Subscription getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Subscription(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              org.bitcoin.protocols.payments.Protos.PaymentDetails.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = contract_.toBuilder();
              }
              contract_ = input.readMessage(org.bitcoin.protocols.payments.Protos.PaymentDetails.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(contract_);
                contract_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                paymentsForPeriod_ = new java.util.ArrayList<org.bitcoin.protocols.payments.Protos.PaymentDetails>();
                mutable_bitField0_ |= 0x00000002;
              }
              paymentsForPeriod_.add(input.readMessage(org.bitcoin.protocols.payments.Protos.PaymentDetails.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          paymentsForPeriod_ = java.util.Collections.unmodifiableList(paymentsForPeriod_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bitcoin.protocols.subscriptions.Protos.internal_static_payments_Subscription_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bitcoin.protocols.subscriptions.Protos.internal_static_payments_Subscription_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.bitcoin.protocols.subscriptions.Protos.Subscription.class, org.bitcoin.protocols.subscriptions.Protos.Subscription.Builder.class);
    }

    public static com.google.protobuf.Parser<Subscription> PARSER =
        new com.google.protobuf.AbstractParser<Subscription>() {
      public Subscription parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Subscription(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Subscription> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .payments.PaymentDetails contract = 1;
    public static final int CONTRACT_FIELD_NUMBER = 1;
    private org.bitcoin.protocols.payments.Protos.PaymentDetails contract_;
    /**
     * <code>required .payments.PaymentDetails contract = 1;</code>
     */
    public boolean hasContract() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .payments.PaymentDetails contract = 1;</code>
     */
    public org.bitcoin.protocols.payments.Protos.PaymentDetails getContract() {
      return contract_;
    }
    /**
     * <code>required .payments.PaymentDetails contract = 1;</code>
     */
    public org.bitcoin.protocols.payments.Protos.PaymentDetailsOrBuilder getContractOrBuilder() {
      return contract_;
    }

    // repeated .payments.PaymentDetails payments_for_period = 2;
    public static final int PAYMENTS_FOR_PERIOD_FIELD_NUMBER = 2;
    private java.util.List<org.bitcoin.protocols.payments.Protos.PaymentDetails> paymentsForPeriod_;
    /**
     * <code>repeated .payments.PaymentDetails payments_for_period = 2;</code>
     */
    public java.util.List<org.bitcoin.protocols.payments.Protos.PaymentDetails> getPaymentsForPeriodList() {
      return paymentsForPeriod_;
    }
    /**
     * <code>repeated .payments.PaymentDetails payments_for_period = 2;</code>
     */
    public java.util.List<? extends org.bitcoin.protocols.payments.Protos.PaymentDetailsOrBuilder> 
        getPaymentsForPeriodOrBuilderList() {
      return paymentsForPeriod_;
    }
    /**
     * <code>repeated .payments.PaymentDetails payments_for_period = 2;</code>
     */
    public int getPaymentsForPeriodCount() {
      return paymentsForPeriod_.size();
    }
    /**
     * <code>repeated .payments.PaymentDetails payments_for_period = 2;</code>
     */
    public org.bitcoin.protocols.payments.Protos.PaymentDetails getPaymentsForPeriod(int index) {
      return paymentsForPeriod_.get(index);
    }
    /**
     * <code>repeated .payments.PaymentDetails payments_for_period = 2;</code>
     */
    public org.bitcoin.protocols.payments.Protos.PaymentDetailsOrBuilder getPaymentsForPeriodOrBuilder(
        int index) {
      return paymentsForPeriod_.get(index);
    }

    private void initFields() {
      contract_ = org.bitcoin.protocols.payments.Protos.PaymentDetails.getDefaultInstance();
      paymentsForPeriod_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasContract()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getContract().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPaymentsForPeriodCount(); i++) {
        if (!getPaymentsForPeriod(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, contract_);
      }
      for (int i = 0; i < paymentsForPeriod_.size(); i++) {
        output.writeMessage(2, paymentsForPeriod_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, contract_);
      }
      for (int i = 0; i < paymentsForPeriod_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, paymentsForPeriod_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.bitcoin.protocols.subscriptions.Protos.Subscription parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bitcoin.protocols.subscriptions.Protos.Subscription parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bitcoin.protocols.subscriptions.Protos.Subscription parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bitcoin.protocols.subscriptions.Protos.Subscription parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bitcoin.protocols.subscriptions.Protos.Subscription parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.bitcoin.protocols.subscriptions.Protos.Subscription parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.bitcoin.protocols.subscriptions.Protos.Subscription parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.bitcoin.protocols.subscriptions.Protos.Subscription parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.bitcoin.protocols.subscriptions.Protos.Subscription parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.bitcoin.protocols.subscriptions.Protos.Subscription parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.bitcoin.protocols.subscriptions.Protos.Subscription prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code payments.Subscription}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.bitcoin.protocols.subscriptions.Protos.SubscriptionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.bitcoin.protocols.subscriptions.Protos.internal_static_payments_Subscription_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.bitcoin.protocols.subscriptions.Protos.internal_static_payments_Subscription_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.bitcoin.protocols.subscriptions.Protos.Subscription.class, org.bitcoin.protocols.subscriptions.Protos.Subscription.Builder.class);
      }

      // Construct using org.bitcoin.protocols.subscriptions.Protos.Subscription.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getContractFieldBuilder();
          getPaymentsForPeriodFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (contractBuilder_ == null) {
          contract_ = org.bitcoin.protocols.payments.Protos.PaymentDetails.getDefaultInstance();
        } else {
          contractBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (paymentsForPeriodBuilder_ == null) {
          paymentsForPeriod_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          paymentsForPeriodBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.bitcoin.protocols.subscriptions.Protos.internal_static_payments_Subscription_descriptor;
      }

      public org.bitcoin.protocols.subscriptions.Protos.Subscription getDefaultInstanceForType() {
        return org.bitcoin.protocols.subscriptions.Protos.Subscription.getDefaultInstance();
      }

      public org.bitcoin.protocols.subscriptions.Protos.Subscription build() {
        org.bitcoin.protocols.subscriptions.Protos.Subscription result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.bitcoin.protocols.subscriptions.Protos.Subscription buildPartial() {
        org.bitcoin.protocols.subscriptions.Protos.Subscription result = new org.bitcoin.protocols.subscriptions.Protos.Subscription(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (contractBuilder_ == null) {
          result.contract_ = contract_;
        } else {
          result.contract_ = contractBuilder_.build();
        }
        if (paymentsForPeriodBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            paymentsForPeriod_ = java.util.Collections.unmodifiableList(paymentsForPeriod_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.paymentsForPeriod_ = paymentsForPeriod_;
        } else {
          result.paymentsForPeriod_ = paymentsForPeriodBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.bitcoin.protocols.subscriptions.Protos.Subscription) {
          return mergeFrom((org.bitcoin.protocols.subscriptions.Protos.Subscription)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.bitcoin.protocols.subscriptions.Protos.Subscription other) {
        if (other == org.bitcoin.protocols.subscriptions.Protos.Subscription.getDefaultInstance()) return this;
        if (other.hasContract()) {
          mergeContract(other.getContract());
        }
        if (paymentsForPeriodBuilder_ == null) {
          if (!other.paymentsForPeriod_.isEmpty()) {
            if (paymentsForPeriod_.isEmpty()) {
              paymentsForPeriod_ = other.paymentsForPeriod_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensurePaymentsForPeriodIsMutable();
              paymentsForPeriod_.addAll(other.paymentsForPeriod_);
            }
            onChanged();
          }
        } else {
          if (!other.paymentsForPeriod_.isEmpty()) {
            if (paymentsForPeriodBuilder_.isEmpty()) {
              paymentsForPeriodBuilder_.dispose();
              paymentsForPeriodBuilder_ = null;
              paymentsForPeriod_ = other.paymentsForPeriod_;
              bitField0_ = (bitField0_ & ~0x00000002);
              paymentsForPeriodBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPaymentsForPeriodFieldBuilder() : null;
            } else {
              paymentsForPeriodBuilder_.addAllMessages(other.paymentsForPeriod_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasContract()) {
          
          return false;
        }
        if (!getContract().isInitialized()) {
          
          return false;
        }
        for (int i = 0; i < getPaymentsForPeriodCount(); i++) {
          if (!getPaymentsForPeriod(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.bitcoin.protocols.subscriptions.Protos.Subscription parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.bitcoin.protocols.subscriptions.Protos.Subscription) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .payments.PaymentDetails contract = 1;
      private org.bitcoin.protocols.payments.Protos.PaymentDetails contract_ = org.bitcoin.protocols.payments.Protos.PaymentDetails.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.bitcoin.protocols.payments.Protos.PaymentDetails, org.bitcoin.protocols.payments.Protos.PaymentDetails.Builder, org.bitcoin.protocols.payments.Protos.PaymentDetailsOrBuilder> contractBuilder_;
      /**
       * <code>required .payments.PaymentDetails contract = 1;</code>
       */
      public boolean hasContract() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .payments.PaymentDetails contract = 1;</code>
       */
      public org.bitcoin.protocols.payments.Protos.PaymentDetails getContract() {
        if (contractBuilder_ == null) {
          return contract_;
        } else {
          return contractBuilder_.getMessage();
        }
      }
      /**
       * <code>required .payments.PaymentDetails contract = 1;</code>
       */
      public Builder setContract(org.bitcoin.protocols.payments.Protos.PaymentDetails value) {
        if (contractBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          contract_ = value;
          onChanged();
        } else {
          contractBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .payments.PaymentDetails contract = 1;</code>
       */
      public Builder setContract(
          org.bitcoin.protocols.payments.Protos.PaymentDetails.Builder builderForValue) {
        if (contractBuilder_ == null) {
          contract_ = builderForValue.build();
          onChanged();
        } else {
          contractBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .payments.PaymentDetails contract = 1;</code>
       */
      public Builder mergeContract(org.bitcoin.protocols.payments.Protos.PaymentDetails value) {
        if (contractBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              contract_ != org.bitcoin.protocols.payments.Protos.PaymentDetails.getDefaultInstance()) {
            contract_ =
              org.bitcoin.protocols.payments.Protos.PaymentDetails.newBuilder(contract_).mergeFrom(value).buildPartial();
          } else {
            contract_ = value;
          }
          onChanged();
        } else {
          contractBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .payments.PaymentDetails contract = 1;</code>
       */
      public Builder clearContract() {
        if (contractBuilder_ == null) {
          contract_ = org.bitcoin.protocols.payments.Protos.PaymentDetails.getDefaultInstance();
          onChanged();
        } else {
          contractBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .payments.PaymentDetails contract = 1;</code>
       */
      public org.bitcoin.protocols.payments.Protos.PaymentDetails.Builder getContractBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getContractFieldBuilder().getBuilder();
      }
      /**
       * <code>required .payments.PaymentDetails contract = 1;</code>
       */
      public org.bitcoin.protocols.payments.Protos.PaymentDetailsOrBuilder getContractOrBuilder() {
        if (contractBuilder_ != null) {
          return contractBuilder_.getMessageOrBuilder();
        } else {
          return contract_;
        }
      }
      /**
       * <code>required .payments.PaymentDetails contract = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.bitcoin.protocols.payments.Protos.PaymentDetails, org.bitcoin.protocols.payments.Protos.PaymentDetails.Builder, org.bitcoin.protocols.payments.Protos.PaymentDetailsOrBuilder> 
          getContractFieldBuilder() {
        if (contractBuilder_ == null) {
          contractBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.bitcoin.protocols.payments.Protos.PaymentDetails, org.bitcoin.protocols.payments.Protos.PaymentDetails.Builder, org.bitcoin.protocols.payments.Protos.PaymentDetailsOrBuilder>(
                  contract_,
                  getParentForChildren(),
                  isClean());
          contract_ = null;
        }
        return contractBuilder_;
      }

      // repeated .payments.PaymentDetails payments_for_period = 2;
      private java.util.List<org.bitcoin.protocols.payments.Protos.PaymentDetails> paymentsForPeriod_ =
        java.util.Collections.emptyList();
      private void ensurePaymentsForPeriodIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          paymentsForPeriod_ = new java.util.ArrayList<org.bitcoin.protocols.payments.Protos.PaymentDetails>(paymentsForPeriod_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.bitcoin.protocols.payments.Protos.PaymentDetails, org.bitcoin.protocols.payments.Protos.PaymentDetails.Builder, org.bitcoin.protocols.payments.Protos.PaymentDetailsOrBuilder> paymentsForPeriodBuilder_;

      /**
       * <code>repeated .payments.PaymentDetails payments_for_period = 2;</code>
       */
      public java.util.List<org.bitcoin.protocols.payments.Protos.PaymentDetails> getPaymentsForPeriodList() {
        if (paymentsForPeriodBuilder_ == null) {
          return java.util.Collections.unmodifiableList(paymentsForPeriod_);
        } else {
          return paymentsForPeriodBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .payments.PaymentDetails payments_for_period = 2;</code>
       */
      public int getPaymentsForPeriodCount() {
        if (paymentsForPeriodBuilder_ == null) {
          return paymentsForPeriod_.size();
        } else {
          return paymentsForPeriodBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .payments.PaymentDetails payments_for_period = 2;</code>
       */
      public org.bitcoin.protocols.payments.Protos.PaymentDetails getPaymentsForPeriod(int index) {
        if (paymentsForPeriodBuilder_ == null) {
          return paymentsForPeriod_.get(index);
        } else {
          return paymentsForPeriodBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .payments.PaymentDetails payments_for_period = 2;</code>
       */
      public Builder setPaymentsForPeriod(
          int index, org.bitcoin.protocols.payments.Protos.PaymentDetails value) {
        if (paymentsForPeriodBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePaymentsForPeriodIsMutable();
          paymentsForPeriod_.set(index, value);
          onChanged();
        } else {
          paymentsForPeriodBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .payments.PaymentDetails payments_for_period = 2;</code>
       */
      public Builder setPaymentsForPeriod(
          int index, org.bitcoin.protocols.payments.Protos.PaymentDetails.Builder builderForValue) {
        if (paymentsForPeriodBuilder_ == null) {
          ensurePaymentsForPeriodIsMutable();
          paymentsForPeriod_.set(index, builderForValue.build());
          onChanged();
        } else {
          paymentsForPeriodBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .payments.PaymentDetails payments_for_period = 2;</code>
       */
      public Builder addPaymentsForPeriod(org.bitcoin.protocols.payments.Protos.PaymentDetails value) {
        if (paymentsForPeriodBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePaymentsForPeriodIsMutable();
          paymentsForPeriod_.add(value);
          onChanged();
        } else {
          paymentsForPeriodBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .payments.PaymentDetails payments_for_period = 2;</code>
       */
      public Builder addPaymentsForPeriod(
          int index, org.bitcoin.protocols.payments.Protos.PaymentDetails value) {
        if (paymentsForPeriodBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePaymentsForPeriodIsMutable();
          paymentsForPeriod_.add(index, value);
          onChanged();
        } else {
          paymentsForPeriodBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .payments.PaymentDetails payments_for_period = 2;</code>
       */
      public Builder addPaymentsForPeriod(
          org.bitcoin.protocols.payments.Protos.PaymentDetails.Builder builderForValue) {
        if (paymentsForPeriodBuilder_ == null) {
          ensurePaymentsForPeriodIsMutable();
          paymentsForPeriod_.add(builderForValue.build());
          onChanged();
        } else {
          paymentsForPeriodBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .payments.PaymentDetails payments_for_period = 2;</code>
       */
      public Builder addPaymentsForPeriod(
          int index, org.bitcoin.protocols.payments.Protos.PaymentDetails.Builder builderForValue) {
        if (paymentsForPeriodBuilder_ == null) {
          ensurePaymentsForPeriodIsMutable();
          paymentsForPeriod_.add(index, builderForValue.build());
          onChanged();
        } else {
          paymentsForPeriodBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .payments.PaymentDetails payments_for_period = 2;</code>
       */
      public Builder addAllPaymentsForPeriod(
          java.lang.Iterable<? extends org.bitcoin.protocols.payments.Protos.PaymentDetails> values) {
        if (paymentsForPeriodBuilder_ == null) {
          ensurePaymentsForPeriodIsMutable();
          super.addAll(values, paymentsForPeriod_);
          onChanged();
        } else {
          paymentsForPeriodBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .payments.PaymentDetails payments_for_period = 2;</code>
       */
      public Builder clearPaymentsForPeriod() {
        if (paymentsForPeriodBuilder_ == null) {
          paymentsForPeriod_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          paymentsForPeriodBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .payments.PaymentDetails payments_for_period = 2;</code>
       */
      public Builder removePaymentsForPeriod(int index) {
        if (paymentsForPeriodBuilder_ == null) {
          ensurePaymentsForPeriodIsMutable();
          paymentsForPeriod_.remove(index);
          onChanged();
        } else {
          paymentsForPeriodBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .payments.PaymentDetails payments_for_period = 2;</code>
       */
      public org.bitcoin.protocols.payments.Protos.PaymentDetails.Builder getPaymentsForPeriodBuilder(
          int index) {
        return getPaymentsForPeriodFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .payments.PaymentDetails payments_for_period = 2;</code>
       */
      public org.bitcoin.protocols.payments.Protos.PaymentDetailsOrBuilder getPaymentsForPeriodOrBuilder(
          int index) {
        if (paymentsForPeriodBuilder_ == null) {
          return paymentsForPeriod_.get(index);  } else {
          return paymentsForPeriodBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .payments.PaymentDetails payments_for_period = 2;</code>
       */
      public java.util.List<? extends org.bitcoin.protocols.payments.Protos.PaymentDetailsOrBuilder> 
           getPaymentsForPeriodOrBuilderList() {
        if (paymentsForPeriodBuilder_ != null) {
          return paymentsForPeriodBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(paymentsForPeriod_);
        }
      }
      /**
       * <code>repeated .payments.PaymentDetails payments_for_period = 2;</code>
       */
      public org.bitcoin.protocols.payments.Protos.PaymentDetails.Builder addPaymentsForPeriodBuilder() {
        return getPaymentsForPeriodFieldBuilder().addBuilder(
            org.bitcoin.protocols.payments.Protos.PaymentDetails.getDefaultInstance());
      }
      /**
       * <code>repeated .payments.PaymentDetails payments_for_period = 2;</code>
       */
      public org.bitcoin.protocols.payments.Protos.PaymentDetails.Builder addPaymentsForPeriodBuilder(
          int index) {
        return getPaymentsForPeriodFieldBuilder().addBuilder(
            index, org.bitcoin.protocols.payments.Protos.PaymentDetails.getDefaultInstance());
      }
      /**
       * <code>repeated .payments.PaymentDetails payments_for_period = 2;</code>
       */
      public java.util.List<org.bitcoin.protocols.payments.Protos.PaymentDetails.Builder> 
           getPaymentsForPeriodBuilderList() {
        return getPaymentsForPeriodFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.bitcoin.protocols.payments.Protos.PaymentDetails, org.bitcoin.protocols.payments.Protos.PaymentDetails.Builder, org.bitcoin.protocols.payments.Protos.PaymentDetailsOrBuilder> 
          getPaymentsForPeriodFieldBuilder() {
        if (paymentsForPeriodBuilder_ == null) {
          paymentsForPeriodBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.bitcoin.protocols.payments.Protos.PaymentDetails, org.bitcoin.protocols.payments.Protos.PaymentDetails.Builder, org.bitcoin.protocols.payments.Protos.PaymentDetailsOrBuilder>(
                  paymentsForPeriod_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          paymentsForPeriod_ = null;
        }
        return paymentsForPeriodBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:payments.Subscription)
    }

    static {
      defaultInstance = new Subscription(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:payments.Subscription)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_payments_Subscription_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_payments_Subscription_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022subscription.proto\022\010payments\032\024paymentr" +
      "equest.proto\"q\n\014Subscription\022*\n\010contract" +
      "\030\001 \002(\0132\030.payments.PaymentDetails\0225\n\023paym" +
      "ents_for_period\030\002 \003(\0132\030.payments.Payment" +
      "DetailsB-\n#org.bitcoin.protocols.subscri" +
      "ptionsB\006Protos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_payments_Subscription_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_payments_Subscription_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_payments_Subscription_descriptor,
              new java.lang.String[] { "Contract", "PaymentsForPeriod", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.bitcoin.protocols.payments.Protos.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
